<?php
$a[]="Kapor Capital";
$a[]="Mitch Kapor";
$a[]="SoftTech";
$a[]="Highland Capital";
$a[]="General Catalyst"
$a[]="New Markets Ventures";
$a[]="NSVF";
$a[]="Retink Education";
$a[]="Matt Greenfield";
$a[]="Jennifer Carolan";
$a[]="Zac Zeitlin";
$a[]="Don Kendall";
$a[]="Catamount Ventures";
$a[]="Raymond Capital";
$a[]="Kauffman Foundation";
$a[]="Birchmere Ventues";
$a[]="Jean Hammond";
$a[]="Accel Partners";
$a[]="SV Angel";
$a[]="Paul Graham";
$a[]="David Jeske";
$a[]="Joe Greenstein";
$a[]="Shasta Venture";
$a[]="Sequoia Partners";
$a[]="Kleiner Perkins";
?>